version: "3.9"
services:
  backend:
    build: .
    command: bash -c " uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
